name: CI

on:
  push:
  pull_request:

env:
  # Docker tag for the production image
  LATEST_IMAGE_NAME: ghcr.io/qwex23/chicken-api:latest
  # Docker tag that includes the current commit SHA
  COMMIT_IMAGE_NAME: ghcr.io/qwex23/chicken-api:${{ github.sha }}

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - name: Run spotless and build
        run: ./gradlew spotlessCheck build --no-daemon
      - name: Log in to GHCR
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Determine Docker tags
        if: github.event_name == 'push'
        id: tags
        run: |
          tags="${{ env.COMMIT_IMAGE_NAME }}"
          if [[ "$GITHUB_REF" == 'refs/heads/main' ]]; then
            tags="$tags,${{ env.LATEST_IMAGE_NAME }}"
          fi
          echo "tags=$tags" >> "$GITHUB_OUTPUT"
      - name: Build and push Docker image
        if: github.event_name == 'push'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.tags.outputs.tags }}
